### ISSUE TITLE
Keys generated by php-libsodium can not be reproduced by libgodium

### ISSUE THREAD

**Issue by vzool** [ArteMisc/libgodium#4]
Hi, I have a `PublicKey` derived from `SecretKey` generated by [sodium_crypto_box_publickey_from_secretkey](https://paragonie.com/book/pecl-libsodium/read/08-advanced.md#public-key-from-secret-key) in project [paragonie/sapient](https://github.com/paragonie/sapient) and I'm trying to repeat key generation steps by [ArteMisc/libgodium](https://github.com/ArteMisc/libgodium) in order to make a library that can help community to communicate securely between `PHP` and `golang` projects but I failed. So here is the code snippet for my current situation:

```golang
// secretKey(base64URLEncoded-64bytes): "YXh13GLZzaQRNIIdoYAwymqCqsLjaKfk9bR_Il7H0c0nVjUUBNklDy7OZRJgE8Cz_VWHENAOTJo_sKSiJGVFgw=="
// publicKey(base64URLEncoded-32bytes): "jpKz5zYpVfeNxQYmkOmUIAa8lZpH2RlK2ZPiG_XEnZI="
// Above public Key generated by sodium_crypto_box_publickey_from_secretkey

// Same keys in Hex format
secretKeyStr := "617875dc62d9cda41134821da18030ca6a82aac2e368a7e4f5b47f225ec7d1cd2756351404d9250f2ece65126013c0b3fd558710d00e4c9a3fb0a4a224654583"
publicKeyStr := "8e92b3e7362955f78dc5062690e9942006bc959a47d9194ad993e21bf5c49d92"
secretKey, _ := hex.DecodeString(secretKeyStr)
publicKey, _ := hex.DecodeString(publicKeyStr)

godiumPublicKey := hex.EncodeToString(
	sign.New(secretKey[:]).PublicKey(),
)

fmt.Println("Match:", godiumPublicKey == publicKeyStr)
fmt.Println("godium PublicKey:", godiumPublicKey)
fmt.Println("original PublicKey:", publicKeyStr)
```

### Output

```shell
Match: false
godium PublicKey: 2756351404d9250f2ece65126013c0b3fd558710d00e4c9a3fb0a4a224654583
original PublicKey: 8e92b3e7362955f78dc5062690e9942006bc959a47d9194ad993e21bf5c49d92
```

**Note**: if you like to decode original keys use [kalaspuffar/base64url](https://github.com/kalaspuffar/base64url)

Thanks

**Comment by ArteMisc** [comment]
It appears you are mixing up two different algorithms here.

In the PHP example you refer to sodium_crypto_**box**_publickey_from_secretkey, but your Go code refers to **sign**.New().PublicKey().

The Box algorithm uses X25519 keys, the Sign algorithm uses ed25519. Deriving the public key for X25519 is currently not exposed in the Box interface, so for the time being you're probably looking for `godiumPublicKey := scalarmult.Curve25519Base(nil, secretKey)` or `godiumPublicKey := scalarmult.ScalarMultBase(nil, secretKey)`, the latter of which just wraps the Curve25519Base function.

That being said, I will revisit the API to make these kinds of operations easier to use / find.

**Comment by EricKim65** [comment]
Hi ArteMisc.
First of all, I am very thankful and feel gratitude to your contribution for developer community.

I am a Korean golang developer who want to start a project for php-laravel frontend and Golang backend.
Since this is a mission-critical project, I want to make sure that godium has successful example code as following:

1) php-sodium code : encrytion

============ php code =========
$keyPair = sodium_crypto_box_keypair();
$publicKey = sodium_crypto_box_publickey($keyPair);
$secretKey = sodium_crypto_box_secretkey($keyPair);

//from client generate encrypt key
$msg = 'database config';
$encrypted = sodium_crypto_box_seal($msg, $publicKey);

$decrypted = sodium_crypto_box_seal_open($encrypted, $keyPair)

=============================

2) decryption using the keyPair in godium.
 
Pls let me know if you have example golang code of decryption for me to prove it successfully decrypted in cross-languages
Otherwise a minor hint and page link will be a big help for me to solve this problem.
I want to pay your effort or help for your kindness in any other way.

hope the message can reach you soon and get some feedback.
have a good day.
